name: CI - Booking API Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 7 * * *' 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-rerunfailures  # optional if using rerun plugin

      - name: Run full pytest suite
        run: |
          mkdir -p reports
          pytest --html=reports/booker-api-testing-report.html --self-contained-html --cache-clear
        continue-on-error: true

      - name: Retry only failed tests
        run: |
          pytest --last-failed --html=reports/booker-api-testing-report-retry.html --self-contained-html
        continue-on-error: true

      - name: Upload HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: |
            reports/booker-api-testing-report.html
            reports/booker-api-testing-report-retry.html
