name: CI - Booking API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full pytest suite
        run: |
          mkdir -p reports
          mkdir -p allure-results
          pytest --html=reports/booker-api-testing-report.html \
                 --self-contained-html \
                 --alluredir=allure-results \
                 --cache-clear
        continue-on-error: true

      - name: Retry only failed tests
        run: |
          pytest --last-failed \
                 --html=reports/booker-api-testing-report-retry.html \
                 --self-contained-html \
                 --alluredir=allure-results
        continue-on-error: true

      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install allure -y

      - name: Generate Allure HTML report
        run: |
          mkdir -p reports/allure-html
          allure generate allure-results --clean -o reports/allure-html
        continue-on-error: true

      - name: Upload HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-reports
          path: |
            reports/booker-api-testing-report.html
            reports/booker-api-testing-report-retry.html

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-html
